version: "3"
services:
    api:
        build: ./api
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - api
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - api
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
